name: Generate diagrams

on:
  push:
    branches: [ main, feature/c4-plantuml-actions ]
    paths:
      - 'docs/diagrams/**.puml'

jobs:
  render_diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # Usamos Java 11 para máxima compatibilidad con versiones viejas de PlantUML

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Render con PlantUML
        run: |
          mkdir -p docs/diagrams
          
          # Descargar una versión ultra-estable
          curl -L https://github.com/plantuml/plantuml/releases/download/v1.2022.7/plantuml-1.2022.7.jar -o ./plantuml-engine.jar
          
          # Ejecutar forzando UTF-8 y permitiendo inclusiones
          java -Dfile.encoding=UTF-8 -Dallow_include=true -jar ./plantuml-engine.jar -tsvg docs/diagrams/c4-container.puml

      - name: Push results
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/diagrams/c4-container.svg
          
          if git diff --cached --quiet; then
            echo "No hay cambios."
          else
            git commit -m "docs: generate c4 diagram [skip ci]"
            git push origin ${{ github.ref_name }}
          fi